name: TestProject
options:
  bundleIdPrefix: com.pixelcrafter
  xcodeVersion: '15.0'
  deploymentTarget: '15.0'
  groupSortPosition: top
  generateEmptyDirectories: true
  minimumXcodeGenVersion: '2.42.0'
  createIntermediateGroups: true
  useBaseInternationalization: true
  indentWidth: 2
  tabWidth: 2
  usesTabs: false

settings:
  base:
    xcconfig: Config/Base.xcconfig
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    # Добавляем глобальные настройки Asset Catalog для SPM
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
  configs:
    Debug:
      xcconfig: Config/Debug.xcconfig
    Release:
      xcconfig: Config/Release.xcconfig

groups:
  Sources:
    path: Sources
    sourceTree: "<group>"
    createIntermediateGroups: true
    children:
      App:
        path: Sources/App
        sourceTree: "<group>"
        createIntermediateGroups: true
      UI:
        path: Sources/UI
        sourceTree: "<group>"
        createIntermediateGroups: true
        children:
          Screens:
            path: Sources/UI/Screens
            sourceTree: "<group>"
            createIntermediateGroups: true
          Common:
            path: Sources/UI/Common
            sourceTree: "<group>"
            createIntermediateGroups: true
      Models:
        path: Sources/Models
        sourceTree: "<group>"
        createIntermediateGroups: true
      Services:
        path: Sources/Services
        sourceTree: "<group>"
        createIntermediateGroups: true
      Utils:
        path: Sources/Utils
        sourceTree: "<group>"
        createIntermediateGroups: true
  Resources:
    path: Resources
    sourceTree: "<group>"
    createIntermediateGroups: true
    children:
      Assets:
        path: Resources/Assets.xcassets
        sourceTree: "<group>"
        type: folder
      Localization:
        path: Resources/Localization
        sourceTree: "<group>"
        type: folder
      Fonts:
        path: Resources/Fonts
        sourceTree: "<group>"
        type: folder
        optional: true
      LaunchScreen:
        path: Resources/LaunchScreen.storyboard
        sourceTree: "<group>"
        type: file
  Tests:
    path: Tests
    sourceTree: "<group>"
    createIntermediateGroups: true
    children:
      UnitTests:
        path: Tests/UnitTests
        sourceTree: "<group>"
        createIntermediateGroups: true
      UITests:
        path: Tests/UITests
        sourceTree: "<group>"
        createIntermediateGroups: true
        optional: true
  Config:
    path: Config
    sourceTree: "<group>"
    createIntermediateGroups: true

targets:
  TestProject:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
        createIntermediateGroups: true
      - path: Config
        createIntermediateGroups: true
        type: folder
        optional: true
        buildPhase: none
    resources:
      - path: Resources
        createIntermediateGroups: true
    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: false
        UIStatusBarHidden: false
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: true
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
    entitlements:
      path: Sources/TestProject.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixelcrafter.testproject
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        # Явные настройки Asset Catalog для основного таргета и SPM
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  TestProjectTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/UnitTests
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER).tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TestProject.app/TestProject"
    dependencies:
      - target: TestProject

  TestProjectUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/UITests
        createIntermediateGroups: true
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER).uitests
    dependencies:
      - target: TestProject

schemes:
  TestProjectDebug:
    build:
      targets:
        TestProject: [run, test]
        TestProjectTests: [test]
        TestProjectUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
    test:
      targets:
        - TestProjectTests
        - name: TestProjectUITests
          parallelizable: true
          randomExecutionOrder: true
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - TestProject
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      customArchiveName: TestProject
      revealArchiveInOrganizer: true

  TestProjectRelease:
    build:
      targets:
        TestProject: [run, test]
        TestProjectTests: [test]
        TestProjectUITests: [test]
    run:
      config: Release
    test:
      targets:
        - TestProjectTests
        - name: TestProjectUITests
          parallelizable: true
          randomExecutionOrder: true
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
      customArchiveName: TestProject
      revealArchiveInOrganizer: true 